Cs account pt01 03
Sopan-Patil/PlatformTesting pull request #11
Opened 2021-08-06 13:37 UTC by csonparote

Feature: Create account with new user

@PF_CreateAccount @Full
Scenario: Create new account with valid details
Given User is on home page
When User begins account creation
And creates new credentials
And enters confirmation code
And enters valid details
And confirms details
Then Validate that new account is created
#Navigate to home page

@PF_CreateAccountInvalidEmail
Scenario: Create new account with invalid email id
Given User is on home page
When User begins account creation
And User enters invalid email
Then Validate error message is displayed

2021-08-10 05:59 UTC, Sopan-Patil requested changes

2021-08-10 05:59 UTC, Sopan-Patil commented on platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep1.java
> +		// span[contains(text(),'メールアドレスは、メールアドレス形式で入力してください。')]
Please remove unwanted comment code

2021-08-10 05:59 UTC, Sopan-Patil commented on platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep5.java
> +		// XLHandler.writeToExcel("NewUser", "NewTestData.xlsx", 0,
Please remove unwanted comment code

2021-08-10 05:59 UTC, Sopan-Patil commented on platform/src/test/java/platformfeatures/PF_CreateAccount.feature
>  #Navigate to home page
remove commneted step

2021-08-10 05:59 UTC, Sopan-Patil commented on platform/src/test/java/platformstepdefinition/PF_CreateAccount.java
> +		// Assert.assertTrue(loginPage.logoutButton.isDisplayed());
Remove commented code

2021-08-10 05:59 UTC, Sopan-Patil commented on platform/src/test/java/platformstepdefinition/PF_CreateAccount.java
> +		createAccountStep1.validateErrorMessage(createAccountStep1.errorMessageText, "メールアドレスは、メールアドレス形式で入力してください。");
content should not be hard coded.

2021-08-11 10:04 UTC, csonparote commented on platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep1.java
> +		// span[contains(text(),'メールアドレスは、メールアドレス形式で入力してください。')]
done

2021-08-11 10:04 UTC, csonparote commented on platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep5.java
> +		// XLHandler.writeToExcel("NewUser", "NewTestData.xlsx", 0,
done

2021-08-11 10:04 UTC, csonparote commented on platform/src/test/java/platformfeatures/PF_CreateAccount.feature
>  #Navigate to home page
done

2021-08-11 10:04 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_CreateAccount.java
> +		// Assert.assertTrue(loginPage.logoutButton.isDisplayed());
done

2021-08-11 10:12 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_CreateAccount.java
> +		createAccountStep1.validateErrorMessage(createAccountStep1.errorMessageText, "メールアドレスは、メールアドレス形式で入力してください。");
done

2021-08-11 10:22 UTC, csonparote commented
done necessary changes. Please review changed files

2021-08-12 05:15 UTC, Sopan-Patil approved these changes

2021-08-12 05:15 UTC, merged