Rahul order pt62 pt89
Sopan-Patil/PlatformTesting pull request #16
Opened 2021-08-13 05:54 UTC by RahulSmartcloudPFQA

```
Feature: Validate order flow

@OrderWithExistingCreditCard @Smoke @Full 
Scenario: Validate order with Existing valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 page proceed to next page
And Step 3 page proceed to next page
And Verify thank you page for credit card transaction
And Verify thank you page data on order history page for credit card transaction
And logout

@OrderWithCreditCardValid @Smoke @Full
Scenario: Validate order with valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Valid Credit Card
And Step 3 page proceed to next page
And Verify thank you page for credit card transaction
And Verify thank you page data on order history page for credit card transaction
And logout

@OrderWithCreditCardInValid @Smoke @Full
Scenario: Validate order with In valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With InValid Credit Card
And logout

@OrderWithCreditCardBlankValid @Smoke @Full
Scenario: Validate order with Blank valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Blank Credit Card
And logout

@OrderWithConvenienceStoreValid @Smoke @Full
Scenario: Validate order with valid con store

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Valid Convenience Store
And Step 3 page proceed to next page
And Verify thank you page for convenience store transaction
And Verify thank you page data on order history page for convenience store transaction
And logout

@OrderWithConvenienceStoreInValid @Smoke @Full
Scenario: Validate order with invalid con store

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With InValid Convenience Store
And logout

@OrderWithConvenienceStoreBlank @Smoke @Full
Scenario: Validate order with Blank Con store

Given Login To Platform Portal
And Select 1st product from product list page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Blank Con Store
And logout

@OrderPrimeWithValidCreditCard @Smoke @Full
Scenario: Validate prime with valid Credit Card and check on order history,service you are using and membership page

Given Login To Platform Portal
And Open MemberShip Plan Page from Top page
And Apply MemberShip Plan from Top page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Valid Credit Card
And Step 3 page proceed to next page
And Verify thank you page for prime transaction
And Verify thank you page data on order history page for prime transaction
And Verify Service you are using page for prime transaction
And Verify Membership status page for prime transaction

@OrderRefreshPageWithExistingCreditCard  @Full
Scenario: Validate refresh page for order with Existing valid Credit Card

Given Login To Platform Portal
And Open Product List Page
And Refresh page
And Select 1st product from product list page
And Confirm Order Flow Step 1 Page Load Successfully
And Refresh page
And Step 1 page proceed to next page
And Reglogin between Step 1 page to Step 2 page
And Confirm Order Flow Step 2 Page Load Successfully
And Refresh page
And Step 2 page proceed to next page
And Confirm Order Flow Step 3 Page Load Successfully
And Refresh page
And Step 3 page proceed to next page
And Confirm Order Flow Step 4 thank you Page Load Successfully
And Refresh page
And logout

```

2021-08-13 06:16 UTC, csonparote requested changes
Please make changes

2021-08-13 06:16 UTC, csonparote commented on platform/src/main/java/platform/pageobjects/Authentication/LoginPage.java
> +
Plz remove commented code

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.methodForOrderFlowStep1(productNameFromProductListPage, productPriceFromProductListPage);
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.methodForOrderFlowStep2(productNameFromProductListPage, productPriceFromProductListPage);
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.methodForOrderFlowStep3(productNameFromProductListPage, productPriceFromProductListPage);
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.orderFlowStep1PageLoadedSuccessfully();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.orderFlowStep2PageLoadedSuccessfully();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.orderFlowStep3PageLoadedSuccessfully();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.orderFlowStep4ThankYouPageLoadedSuccessfully();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.methodForReloginForOrderFlow();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.methodForStep2PaymentWithValidCreditCard();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
> +		orderObj.methodForStep2PaymentWithInValidCreditCard();
Please start method name with a verb
Cant determine what this method does

2021-08-13 06:16 UTC, csonparote commented on platform/src/test/java/platformstepdefinition/PF_Order.java
>  		orderObj.methodForStep2PaymentWithConStore();
Please start method name with a verb
Cant determine what this method does
Please make changes wherever applicable

2021-08-16 10:58 UTC, RahulSmartcloudPFQA commented
```
Feature: Validate order flow

@OrderWithExistingCreditCard @Smoke @Full 
Scenario: Validate order with Existing valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Compare Product Data On Order Step 2 Page
And Compare Product Data On Order Step 3 Page
And Verify thank you page for credit card transaction
And Verify thank you page data on order history page for credit card transaction
And logout

@OrderWithCreditCardValid @Smoke @Full
Scenario: Validate order with valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Valid Credit Card
And Compare Product Data On Order Step 3 Page
And Verify thank you page for credit card transaction
And Verify thank you page data on order history page for credit card transaction
And logout


@OrderWithCreditCardInValid @Smoke @Full
Scenario: Validate order with In valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With InValid Credit Card
And logout

@OrderWithCreditCardBlankValid @Smoke @Full
Scenario: Validate order with Blank valid Credit Card

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Blank Credit Card
And logout

@OrderWithConvenienceStoreValid @Smoke @Full
Scenario: Validate order with valid con store

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Valid Convenience Store
And Compare Product Data On Order Step 3 Page
And Verify thank you page for convenience store transaction
And Verify thank you page data on order history page for convenience store transaction
And logout

@OrderWithConvenienceStoreInValid @Smoke @Full
Scenario: Validate order with invalid con store

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With InValid Convenience Store
And logout

@OrderWithConvenienceStoreBlank @Smoke @Full
Scenario: Validate order with Blank Con store

Given Login To Platform Portal
And Select 1st product from product list page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Step 2 Payment With Blank Con Store
And logout


@OrderPrimeWithValidCreditCard @Smoke @Full
Scenario: Validate prime with valid Credit Card and check on order history,service you are using and membership page

Given Login To Platform Portal
And Open MemberShip Plan Page from Top page
And Apply MemberShip Plan from Top page
And Compare Prime Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Compare Prime Data On Order Step 2 Page
And Compare Prime Data On Order Step 3 Page
And Verify thank you page for prime transaction
And Verify thank you page data on order history page for prime transaction
And Verify Service you are using page for prime transaction
And Verify Membership status page for prime transaction


@OrderRefreshPageWithExistingCreditCard  @Full
Scenario: Validate refresh page for order with Existing valid Credit Card

Given Login To Platform Portal
And Open Product List Page
And Refresh page
And Select 1st product from product list page
And Verify Order Flow Step 1 Page Loaded Successfully
And Refresh page
And Compare Product Data On Order Step 1 Page
And Reglogin between Step 1 page to Step 2 page
And Verify Order Flow Step 2 Page Loaded Successfully
And Refresh page
And Compare Product Data On Order Step 2 Page
And Verify Order Flow Step 3 Page Loaded Successfully
And Refresh page
And Compare Product Data On Order Step 3 Page
And Verify Order Flow Step 4 Thank You Page Loaded Successfully
And Refresh page
And logout



```

2021-08-16 11:11 UTC, csonparote approved these changes
Plz merge with main

2021-08-16 11:15 UTC, merged